name: orm
version: 0.0.2
environment:
  sdk: '>=1.3.3'
dependencies:
  analyzer: 0.14.2
  html5lib: '>=0.11.0+1 <0.12.0'
  serialization: 0.9.1
  sqljocky: '>=0.11.0 <0.12.0'
  unittest: 0.10.1+2
  utils:
    git: git://github.com/k4rr1m/dart-utils
transformers:
- orm
